# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - master

    docker:
      - image: circleci/android:api-23-alpha
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

      - run:
          name: Install Dependencies
          command: |
              ./gradlew dependencies
              if [ ! -e $ANDROID_HOME/build-tools/23.0.2 ]; then sdkmanager "build-tools;23.0.2"; fi
              if ! $(grep -q "Pkg.Revision=3" $ANDROID_HOME/platforms/android-17/source.properties); then sdkmanager "platforms;android-17"; fi
              if ! $(grep -q "Pkg.Revision=3" $ANDROID_HOME/platforms/android-23/source.properties); then sdkmanager "platforms;android-23"; fi
              if ! $(grep -q "Pkg.Revision=2" $ANDROID_HOME/platforms/android-26/source.properties); then sdkmanager "platforms;android-26"; fi
              if [ ! -e $ANDROID_HOME/add-ons/addon-google_apis-google-17 ]; then sdkmanager "add-ons;addon-google_apis-google-17"; fi
              if [ ! -e $ANDROID_HOME/add-ons/addon-google_apis-google-23 ]; then sdkmanager "add-ons;addon-google_apis-google-23"; fi

      - save_cache:
          paths:
              - ~/.gradle
              - /opt/android/sdk/tools
              - /opt/android/sdk/platforms/android-17
              - /opt/android/sdk/platforms/android-23
              - /opt/android/sdk/platforms/android-26
              - /opt/android/sdk/add-ons/addon-google_apis-google-17/
              - /opt/android/sdk/add-ons/addon-google_apis-google-23/
              - /opt/android/sdk/build-tools/23.0.2/
          key: v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

      - run:
          name: make apk file
          command: ./gradlew clean assembleDebug

      - store_artifacts:
          path: /app/build/outputs/apk/debug/app-debug.apk
          destination: prefix



