# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-23-alpha
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-
          - android-dependencies

      - run:
          name: install gradle dependencies
          command: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Install Android Dependencies
          command: sdkmanager "build-tools;23.0.2" "platforms;android-23" "platforms;android-17" "add-ons;addon-google_apis-google-17" "add-ons;addon-google_apis-google-23"

      - save_cache:
          paths:
            - /opt/android/sdk/tools
            - /opt/android/sdk/platforms/android-17
            - /opt/android/sdk/platforms/android-23
            - /opt/android/sdk/add-ons/addon-google_apis-google-17/
            - /opt/android/sdk/add-ons/addon-google_apis-google-23/
            - /opt/android/sdk/build-tools/23.0.2/
          key: android-dependencies

      - run:
          name: make apk file
          command: ./gradlew clean assembleDebug

      - run: echo "no tests ;)"

      - store_artifacts:
          path: /app/build/outputs/apk/debug/app-debug.apk
          destination: prefix



